// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5yMJ9QXeGNB_Nb69Je6zwBkZo8XrfiOg',
    appId: '1:748945324645:web:a15634d7b7543dd7c4e48c',
    messagingSenderId: '748945324645',
    projectId: 'bankingappx',
    authDomain: 'bankingappx.firebaseapp.com',
    storageBucket: 'bankingappx.firebasestorage.app',
    measurementId: 'G-FHKZ8167VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYHQHycQBf74p2fIFTKEWgYmmQsWRTEkc',
    appId: '1:748945324645:android:400f3b3bb4bc0254c4e48c',
    messagingSenderId: '748945324645',
    projectId: 'bankingappx',
    storageBucket: 'bankingappx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4ebt-0bh4K5bqV94UyOIUuD_zXcitgU',
    appId: '1:748945324645:ios:e760e64f6eeab15bc4e48c',
    messagingSenderId: '748945324645',
    projectId: 'bankingappx',
    storageBucket: 'bankingappx.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG4ebt-0bh4K5bqV94UyOIUuD_zXcitgU',
    appId: '1:748945324645:ios:e760e64f6eeab15bc4e48c',
    messagingSenderId: '748945324645',
    projectId: 'bankingappx',
    storageBucket: 'bankingappx.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5yMJ9QXeGNB_Nb69Je6zwBkZo8XrfiOg',
    appId: '1:748945324645:web:b6ce8b703b564867c4e48c',
    messagingSenderId: '748945324645',
    projectId: 'bankingappx',
    authDomain: 'bankingappx.firebaseapp.com',
    storageBucket: 'bankingappx.firebasestorage.app',
    measurementId: 'G-81YD0C7G7Q',
  );
}
